### ISSUE TITLE
`make Makefiles` creates merge conflicts

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#161]
It's not always a problem, but it very often is.  It would be nice if there was some way to avoid this, by not merging changes to */Makefile at all and instead regenerating them after each merge to master.

I have no idea if anything like this is possible with git, but I thought I'd throw the idea out in case it turns out that there's an easy way to do this.

**Comment by gperciva** [comment]
It _is_ possible with git post-hooks, but I can imagine a number of corner cases that would make it tricky.  Also, it's relatively rare that we have two separate branches that both affect the build system.  This is one area where I think it's not worth automating.

Merge conflicts can be avoided by:
- always putting `Makefile` changes in a separate commit.  (I always call it `build: run 'make Makefiles'`)
- if I suspect there's going to be a conflict, I omit the build-commit from the rebase.
- if there's a commit anyway, I just regenerate the `Makefile`s and do `git add foo/Makefile` so that the latest changes are what's in there.  I don't even need to look at the file contents.

**Comment by gperciva** [comment]
Resolved with the `fix-makefile-conflict.sh` script.
