### ISSUE TITLE
events_network should use poll instead of select

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/libcperciva#6]
select has a hard limit on the highest socket number it supports; poll has the same (less than ideal) performance with large numbers of sockets, but doesn't have any hard limit.  See https://github.com/Tarsnap/spiped/issues/24.

**Comment by gperciva** [comment]
(for the record, I just edited cperciva's comment so that the `spiped#24` was an actual link.  Interestingly, I can see no record that I changed this; even https://github.com/Tarsnap/spiped/issues/24 says "cperciva just referenced this issue".  I guess github issue editing operates on the honour system?)

**Comment by cperciva** [comment]
Ah, thanks -- I thought I used the right syntax and was confused when it didn't autolinkify.

**Comment by gperciva** [comment]
Easiest way: just copy&paste the actual URL.  github automatically turns it into the syntax you see above.

**Comment by mc0** [comment]
Thank you for all of the great tools from your small team. Just pinging this issue to give some feedback.

This one issue makes the usage of spiped way more complicated for anything involving a decent amount of connections on the server end. We are having to set up an haproxy in front of many spiped processes. I'd love to work on this but I think it'd take me a long time to get a handle on all of how libcperciva works with regard to sockets. Also, it looks like spiped has its own version of libcperciva?[1]

Also, would it be better to also add backwards-compat support for epoll as part of this small rewrite?

1: https://github.com/Tarsnap/spiped/tree/master/libcperciva

**Comment by gperciva** [comment]
Hi @mc0,

I can't speak to the epoll / sockets stuff, but I can clarify libcperciva.  The libcperciva files inside spiped should be the same as those found in the libcperciva respository and other Tarsnap repositories.  If you notice a difference, please let us know so that we can update those files.  :)
(that said, spiped does not have all the libcperciva files -- only those relevant to spiped)

**Comment by cperciva** [comment]
@mc0 As @gperciva says, the copy of libcperciva in spiped is a sparse copy which (for the parts used) should be in sync with libcperciva.  Given that most users of libcperciva only take a few functions, it didn't make sense to build libcperciva into shared object files which other programs would use.

You should be able to replace select with poll without touching anything beyond of https://github.com/Tarsnap/libcperciva/blob/master/events/events_network.c .

I'd prefer to start by switching to poll, since that's portable, before adding support for unportable improvements like epoll / kqueue / etc.

**Comment by cperciva** [comment]
Fixed by 91f42f7f50f9e1c61ada00f4724b0d761a4b56c0.
